### ISSUE TITLE
Neotest integration (neotest-jest)

### ISSUE THREAD

**Issue by mxsdev** [mxsdev/nvim-dap-vscode-js#2]
Will require a PR on [neotest-jest](https://github.com/haydenmeade/neotest-jest). Posted here for issue tracking purposes.

**Comment by mxsdev** [comment]
@entropitor 

Hmm, I was able to get jest working with breakpoints, but I was using [this configuration](https://github.com/microsoft/vscode-js-debug/issues/214#issuecomment-572686921). Maybe it's important to keep runtime executable as `node`? 

I'm taking a look at your fork right now, will let you know what I find!

**Comment by entropitor** [comment]
It seems to know the breakpoints and I receive an `event_stopped` in which case it asks for the threads and stackTrace, it receives a response for the threads but non for the stackTrace. So it never gets in this callback: https://github.com/mfussenegger/nvim-dap/blob/master/lua/dap/session.lua#L565-L582. Not sure why... Did you configure your adapter differently? 

(the node vs jest starting doesn't seem to matter because starting through jest ends up running node through the shebang of jest)

**Comment by mxsdev** [comment]
@entropitor 

I took a closer look at this and was able to reproduce a very similar bug. The fix was to include the `cwd` option in the dap configuration. So, for instance, `cwd = "${workspaceFolder}"`. Please try that and let me know if it works.

If that does not work, if you could send me your full request/response log that would be very helpful. 

I also have created a `fix-neotest` branch, which contains a test `./scripts/test -l ./tests/integration/jest_spec.lua`. That will test to see if the `DapStopped` breakpoint gets set in a jest test (using the dap config from your `neotest-jest` fork), and will also create a logfile at `./lib/dap-vscode-js.log` which tracks all session requests/responses. That information could be useful to determine if this is a jest configuration-specific issue. (Note that when running that test, there will be a `Invalid channel id` error in stdout, _this is expected_)

You can also pass a `log_file_level = vim.log.levels.TRACE` to the dap-js setup (again on the `fix-neotest` fork), which creates a logfile at `(stdpath cache)/dap_vscode_js.log`. This log information would be extremely helpful, since it not only prints all dap messages, but it also outputs which child sessions each message is coming from and which of those sessions are the main sessions, as well as internal info from `dap-vscode-js`. If you could run that on your current neotest setup and send the logs, there's a good chance I can figure out why the `stackTrace` callback isn't firing.

**Comment by mxsdev** [comment]
@entropitor 

Oh, and to respond to your question: 

>Did you configure your adapter differently? Are you using latest version of nvim-dap?

Yes to the second question, and technically I used the same config from your fork (I fixed that `end` issue manually). However, I have discovered that whether you use absolute or relative paths can affect the behavior of the debugger in pathological ways. I was able to rectify this only by passing a `cwd` option. I think this might be causing your issue, however without the full json logs I really couldn't say for sure.

**Comment by entropitor** [comment]
The `cwd` doesn't seem to fix it unfortunately.

`./scripts/test -l ./tests/integration/jest_spec.lua` doesn't work but `./scripts/test` does pass (including that subtest)

```
~/.local/share/nvim/site/pack/packer/start/nvim-dap-vscode-js fix-neotest 25s
❯ ./scripts/test -l ./tests/integration/jest_spec.lua

========================================
Testing:        ./tests/integration/jest_spec.lua
Fail    ||      pwa-node jest typescript receives stdout from terminal
            ./lib/plenary.nvim/lua/plenary/async/util.lua:48: bad argument #1 to 'block_on' (table expected, got nil)

            stack traceback:
                ./lib/plenary.nvim/lua/plenary/async/util.lua:48: in function <./lib/plenary.nvim/lua/plenary/async/util.lua:47>

Fail    ||      pwa-node jest typescript with neotest config can acknowledge and continue from breakpoints
            ./lib/plenary.nvim/lua/plenary/async/util.lua:48: bad argument #1 to 'block_on' (table expected, got nil)

            stack traceback:
                ./lib/plenary.nvim/lua/plenary/async/util.lua:48: in function <./lib/plenary.nvim/lua/plenary/async/util.lua:47>


Success:        0
Failed :        2
Errors :        0
========================================
Tests Failed. Exit: 1
Tests failed
```

When I run it with my own project, I get these logs:
[dap_vscode_js.log](https://github.com/mxsdev/nvim-dap-vscode-js/files/9102149/dap_vscode_js.log)
[dap.log](https://github.com/mxsdev/nvim-dap-vscode-js/files/9102155/dap.log)

Notice how the stackTrace doesn't get any response (not even present in dap_vscode_js.log), no matter how long I wait. It seems to send it on the same session/channel as the `threads` request though (guessing from the sequence numbers)

**Comment by entropitor** [comment]
I think my branch on neotest-jest should be okay. It seems like it just doesn't work well together with an old version of jest or something. It seems to work well in the integration.spec.ts directory on this repo.

**Comment by entropitor** [comment]
I've created https://github.com/haydenmeade/neotest-jest/pull/26 to add this support into neotest-jest

**Comment by entropitor** [comment]
I guess this ticket can be closed. Not sure if my issues above are really due to this adapter but maybe more a bug in jest or something. Sometimes it works...

**Comment by mxsdev** [comment]
> I've created [haydenmeade/neotest-jest#26](https://github.com/haydenmeade/neotest-jest/pull/26) to add this support into neotest-jest

Thank you so much for this! Sorry for my sudden inactivity, I got a bit sidetracked with some other matters :)

I've made a separate PR for this issue, see #4. If you could report your jest version that would be very helpful. I did take a look into your log and did not find anything obvious (I was hoping it might be an issue with child processes, but it doesn't seem so, at least not obviously). I haven't done a very thorough investigation into your logfile though.

Really, until I have a reproduction (e.g. a minimal setup with package.json + package-lock.json) I can only speculate. If you can provide that then I'll certainly look further into it! If not, hopefully others will encounter this issue and give some more perspective.
